### ISSUE TITLE
couldn't install this repo on m1 apple 

### ISSUE THREAD

**Issue by Parham-sagharchi** [creativetimofficial/ct-nuxt-argon-dashboard-pro-laravel#8]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [ ] I'm reporting the issue to the correct repository (for multi-repository projects)

# Expected Behavior
 
I would like to install it on a MacBook pro m1.

# Current Behavior

I think that `node-sass@4.14.1` doesn't exist for the `MacBook m1`.
please check this link [node-sass@4.14.1](https://github.com/sass/node-sass/releases/tag/v4.14.1)

it might be a good idea to use the [latest](https://github.com/sass/node-sass/releases/tag/v7.0.3) version of **node-sass** but I need some help to reconfigure the whole of the project according to the latest version of this repo.

## Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. download the pro version
2. `cd nuxt-argon-dashboard-pro-laravel/nuxt-argon-dashboard-pro/`
3.  `node -v ` --> `v14.20.1`
4.  `npm -v ` --> `6.14.17`
5.  `npm install`

with these procedures that I describe for you, I couldn't install them after that I think that might be a good idea to use docker to install this repo with this procedure:

**Dockerfile:**
```
FROM node:14-alpine

WORKDIR /app

RUN apk update && apk upgrade
RUN apk add git

COPY ./package*.json /app/

RUN npm install && npm cache clean --force

COPY . .

ENV PATH ./node_modules/.bin/:$PATH
```
**docker-compose.yml**

```
version: '3.9'
services:
  nuxt:
    build:
      context: .
    image: nuxt_dev
    container_name: nuxt_dev
    command: npm run dev
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "3000:3000"

```

but after using this method, unfortunately, I couldn't install this repo with docker.

## Context

* Device: MacBook M1
* Operating System: macOS Monterey 12.4
* Browser and Version: Chrome Version 106.0.5249.119 (Official Build) (arm64)

## Failure Logs

```

➜  nuxt-argon-dashboard-pro git:(master) ✗ npm install

> fsevents@1.2.13 install /Users/clooner/workspace/SamanProject/nuxt-argon-dashboard-pro-laravel/nuxt-argon-dashboard-pro/node_modules/nodemon/node_modules/fsevents
> node install.js

gyp WARN EACCES current user ("clooner") does not have permission to access the dev dir "/Users/clooner/Library/Caches/node-gyp/14.20.1"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/var/folders/54/p1507fld1z3_06mrsnws4yk00000gn/T/.node-gyp"
  SOLINK_MODULE(target) Release/.node
  CXX(target) Release/obj.target/fse/fsevents.o
  SOLINK_MODULE(target) Release/fse.node

> fsevents@1.2.13 install /Users/clooner/workspace/SamanProject/nuxt-argon-dashboard-pro-laravel/nuxt-argon-dashboard-pro/node_modules/watchpack-chokidar2/node_modules/fsevents
> node install.js

gyp WARN EACCES current user ("clooner") does not have permission to access the dev dir "/Users/clooner/Library/Caches/node-gyp/14.20.1"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/var/folders/54/p1507fld1z3_06mrsnws4yk00000gn/T/.node-gyp"
  SOLINK_MODULE(target) Release/.node
  CXX(target) Release/obj.target/fse/fsevents.o
  SOLINK_MODULE(target) Release/fse.node

> node-sass@4.14.1 install /Users/clooner/workspace/SamanProject/nuxt-argon-dashboard-pro-laravel/nuxt-argon-dashboard-pro/node_modules/node-sass
> node scripts/install.js

Downloading binary from https://github.com/sass/node-sass/releases/download/v4.14.1/darwin-arm64-83_binding.node
Cannot download "https://github.com/sass/node-sass/releases/download/v4.14.1/darwin-arm64-83_binding.node": 

HTTP error 404 Not Found

Hint: If github.com is not accessible in your location
      try setting a proxy via HTTP_PROXY, e.g. 

      export HTTP_PROXY=http://example.com:1234

or configure npm proxy via

      npm config set proxy http://example.com:8080

> core-js@2.6.12 postinstall /Users/clooner/workspace/SamanProject/nuxt-argon-dashboard-pro-laravel/nuxt-argon-dashboard-pro/node_modules/core-js
> node -e "try{require('./postinstall')}catch(e){}"

Thank you for using core-js ( https://github.com/zloirock/core-js ) for polyfilling JavaScript standard library!

The project needs your help! Please consider supporting of core-js on Open Collective or Patreon: 
> https://opencollective.com/core-js 
> https://www.patreon.com/zloirock 

Also, the author of core-js ( https://github.com/zloirock ) is looking for a good job -)


> node-sass@4.14.1 postinstall /Users/clooner/workspace/SamanProject/nuxt-argon-dashboard-pro-laravel/nuxt-argon-dashboard-pro/node_modules/node-sass
> node scripts/build.js

Building: /Users/clooner/.nvm/versions/node/v14.20.1/bin/node /Users/clooner/workspace/SamanProject/nuxt-argon-dashboard-pro-laravel/nuxt-argon-dashboard-pro/node_modules/node-gyp/bin/node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
gyp info it worked if it ends with ok
gyp verb cli [
gyp verb cli   '/Users/clooner/.nvm/versions/node/v14.20.1/bin/node',
gyp verb cli   '/Users/clooner/workspace/SamanProject/nuxt-argon-dashboard-pro-laravel/nuxt-argon-dashboard-pro/node_modules/node-gyp/bin/node-gyp.js',
gyp verb cli   'rebuild',
gyp verb cli   '--verbose',
gyp verb cli   '--libsass_ext=',
gyp verb cli   '--libsass_cflags=',
gyp verb cli   '--libsass_ldflags=',
gyp verb cli   '--libsass_library='
gyp verb cli ]
gyp info using node-gyp@3.8.0
gyp info using node@14.20.1 | darwin | arm64
gyp verb command rebuild []
gyp verb command clean []
gyp verb clean removing "build" directory
gyp verb command configure []
gyp verb check python checking for Python executable "python2" in the PATH
gyp verb `which` failed Error: not found: python2
gyp verb `which` failed     at getNotFoundError (/Users/clooner/workspace/SamanProject/nuxt-argon-dashboard-pro-laravel/nuxt-argon-dashboard-pro/node_modules/node-gyp/node_modules/which/which.js:13:12)
gyp verb `which` failed     at F (/Users/clooner/workspace/SamanProject/nuxt-argon-dashboard-pro-laravel/nuxt-argon-dashboard-pro/node_modules/node-gyp/node_modules/which/which.js:68:19)
gyp verb `which` failed     at E (/Users/clooner/workspace/SamanProject/nuxt-argon-dashboard-pro-laravel/nuxt-argon-dashboard-pro/node_modules/node-gyp/node_modules/which/which.js:80:29)
gyp verb `which` failed     at /Users/clooner/workspace/SamanProject/nuxt-argon-dashboard-pro-laravel/nuxt-argon-dashboard-pro/node_modules/node-gyp/node_modules/which/which.js:89:16
gyp verb `which` failed     at /Users/clooner/workspace/SamanProject/nuxt-argon-dashboard-pro-laravel/nuxt-argon-dashboard-pro/node_modules/isexe/index.js:42:5
gyp verb `which` failed     at /Users/clooner/workspace/SamanProject/nuxt-argon-dashboard-pro-laravel/nuxt-argon-dashboard-pro/node_modules/isexe/mode.js:8:5
gyp verb `which` failed     at FSReqCallback.oncomplete (fs.js:192:21)
gyp verb `which` failed  python2 Error: not found: python2
gyp verb `which` failed     at getNotFoundError (/Users/clooner/workspace/SamanProject/nuxt-argon-dashboard-pro-laravel/nuxt-argon-dashboard-pro/node_modules/node-gyp/node_modules/which/which.js:13:12)
gyp verb `which` failed     at F (/Users/clooner/workspace/SamanProject/nuxt-argon-dashboard-pro-laravel/nuxt-argon-dashboard-pro/node_modules/node-gyp/node_modules/which/which.js:68:19)
gyp verb `which` failed     at E (/Users/clooner/workspace/SamanProject/nuxt-argon-dashboard-pro-laravel/nuxt-argon-dashboard-pro/node_modules/node-gyp/node_modules/which/which.js:80:29)
gyp verb `which` failed     at /Users/clooner/workspace/SamanProject/nuxt-argon-dashboard-pro-laravel/nuxt-argon-dashboard-pro/node_modules/node-gyp/node_modules/which/which.js:89:16
gyp verb `which` failed     at /Users/clooner/workspace/SamanProject/nuxt-argon-dashboard-pro-laravel/nuxt-argon-dashboard-pro/node_modules/isexe/index.js:42:5
gyp verb `which` failed     at /Users/clooner/workspace/SamanProject/nuxt-argon-dashboard-pro-laravel/nuxt-argon-dashboard-pro/node_modules/isexe/mode.js:8:5
gyp verb `which` failed     at FSReqCallback.oncomplete (fs.js:192:21) {
gyp verb `which` failed   code: 'ENOENT'
gyp verb `which` failed }
gyp verb check python checking for Python executable "python" in the PATH
gyp verb `which` failed Error: not found: python
gyp verb `which` failed     at getNotFoundError (/Users/clooner/workspace/SamanProject/nuxt-argon-dashboard-pro-laravel/nuxt-argon-dashboard-pro/node_modules/node-gyp/node_modules/which/which.js:13:12)
gyp verb `which` failed     at F (/Users/clooner/workspace/SamanProject/nuxt-argon-dashboard-pro-laravel/nuxt-argon-dashboard-pro/node_modules/node-gyp/node_modules/which/which.js:68:19)
gyp verb `which` failed     at E (/Users/clooner/workspace/SamanProject/nuxt-argon-dashboard-pro-laravel/nuxt-argon-dashboard-pro/node_modules/node-gyp/node_modules/which/which.js:80:29)
gyp verb `which` failed     at /Users/clooner/workspace/SamanProject/nuxt-argon-dashboard-pro-laravel/nuxt-argon-dashboard-pro/node_modules/node-gyp/node_modules/which/which.js:89:16
gyp verb `which` failed     at /Users/clooner/workspace/SamanProject/nuxt-argon-dashboard-pro-laravel/nuxt-argon-dashboard-pro/node_modules/isexe/index.js:42:5
gyp verb `which` failed     at /Users/clooner/workspace/SamanProject/nuxt-argon-dashboard-pro-laravel/nuxt-argon-dashboard-pro/node_modules/isexe/mode.js:8:5
gyp verb `which` failed     at FSReqCallback.oncomplete (fs.js:192:21)
gyp verb `which` failed  python Error: not found: python
gyp verb `which` failed     at getNotFoundError (/Users/clooner/workspace/SamanProject/nuxt-argon-dashboard-pro-laravel/nuxt-argon-dashboard-pro/node_modules/node-gyp/node_modules/which/which.js:13:12)
gyp verb `which` failed     at F (/Users/clooner/workspace/SamanProject/nuxt-argon-dashboard-pro-laravel/nuxt-argon-dashboard-pro/node_modules/node-gyp/node_modules/which/which.js:68:19)
gyp verb `which` failed     at E (/Users/clooner/workspace/SamanProject/nuxt-argon-dashboard-pro-laravel/nuxt-argon-dashboard-pro/node_modules/node-gyp/node_modules/which/which.js:80:29)
gyp verb `which` failed     at /Users/clooner/workspace/SamanProject/nuxt-argon-dashboard-pro-laravel/nuxt-argon-dashboard-pro/node_modules/node-gyp/node_modules/which/which.js:89:16
gyp verb `which` failed     at /Users/clooner/workspace/SamanProject/nuxt-argon-dashboard-pro-laravel/nuxt-argon-dashboard-pro/node_modules/isexe/index.js:42:5
gyp verb `which` failed     at /Users/clooner/workspace/SamanProject/nuxt-argon-dashboard-pro-laravel/nuxt-argon-dashboard-pro/node_modules/isexe/mode.js:8:5
gyp verb `which` failed     at FSReqCallback.oncomplete (fs.js:192:21) {
gyp verb `which` failed   code: 'ENOENT'
gyp verb `which` failed }
gyp ERR! configure error 
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
gyp ERR! stack     at PythonFinder.failNoPython (/Users/clooner/workspace/SamanProject/nuxt-argon-dashboard-pro-laravel/nuxt-argon-dashboard-pro/node_modules/node-gyp/lib/configure.js:484:19)
gyp ERR! stack     at PythonFinder.<anonymous> (/Users/clooner/workspace/SamanProject/nuxt-argon-dashboard-pro-laravel/nuxt-argon-dashboard-pro/node_modules/node-gyp/lib/configure.js:406:16)
gyp ERR! stack     at F (/Users/clooner/workspace/SamanProject/nuxt-argon-dashboard-pro-laravel/nuxt-argon-dashboard-pro/node_modules/node-gyp/node_modules/which/which.js:68:16)
gyp ERR! stack     at E (/Users/clooner/workspace/SamanProject/nuxt-argon-dashboard-pro-laravel/nuxt-argon-dashboard-pro/node_modules/node-gyp/node_modules/which/which.js:80:29)
gyp ERR! stack     at /Users/clooner/workspace/SamanProject/nuxt-argon-dashboard-pro-laravel/nuxt-argon-dashboard-pro/node_modules/node-gyp/node_modules/which/which.js:89:16
gyp ERR! stack     at /Users/clooner/workspace/SamanProject/nuxt-argon-dashboard-pro-laravel/nuxt-argon-dashboard-pro/node_modules/isexe/index.js:42:5
gyp ERR! stack     at /Users/clooner/workspace/SamanProject/nuxt-argon-dashboard-pro-laravel/nuxt-argon-dashboard-pro/node_modules/isexe/mode.js:8:5
gyp ERR! stack     at FSReqCallback.oncomplete (fs.js:192:21)
gyp ERR! System Darwin 21.5.0
gyp ERR! command "/Users/clooner/.nvm/versions/node/v14.20.1/bin/node" "/Users/clooner/workspace/SamanProject/nuxt-argon-dashboard-pro-laravel/nuxt-argon-dashboard-pro/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd /Users/clooner/workspace/SamanProject/nuxt-argon-dashboard-pro-laravel/nuxt-argon-dashboard-pro/node_modules/node-sass
gyp ERR! node -v v14.20.1
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
Build failed with error code: 1
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-sass@4.14.1 postinstall: `node scripts/build.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-sass@4.14.1 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/clooner/.npm/_logs/2022-10-20T12_15_46_488Z-debug.log

```

**Comment by teamupdivision** [comment]
Hello, 

Thank you for using Creative Tim products. 

Yes you ca go ahead and install the latest version of node-sass, Unfortunately we cannot help you with this issue as we use a different operating system and we cannot recreate the issues. 

Thank you.

**Comment by Parham-sagharchi** [comment]
thank you
